apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-{{ .Release.Namespace }}
spec:
  acme:
    email: vadim.garifullin.2015@mail.ru
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ .Release.Namespace }}-private-key
    solvers:
    - http01:
        ingress:
          class: nginx